### PR TITLE
Add litedram.core.crossbar tests

### PR DESCRIPTION
**Pull request by jedrzejboczar**
Closes https://github.com/enjoy-digital/litedram/issues/155.

This PR adds core.crossbar tests of address mapping, arbitration, locking and different port types. It also includes a small fix of core.bankmachine tests.

### CODE REVIEW

**Comment by jedrzejboczar** [comment]
Unit tests are ok, Travis failed later when downloading packages during simulations.

**Comment by mithro** [comment]
@jedrzejboczar - You should be able to restart a failed travis build? Can you see if you can see it in the Travis UI?

**Comment by jedrzejboczar** [comment]
Hmm, I can't see any option for that:
screenshot_2020-04-10_16-21-22
I've checked that I am signed in. Should it appear on the right as shown [here](https://stackoverflow.com/a/17624403/8385882)? I've tried to check it on a repo to which I have write access and I couldn't find it either. It is confusing, as I can remember that I was able to restart builds, at least for repos with write access, so I wonder what I am missing.

**Comment by jedrzejboczar** [comment]
Ok, sorry for confusing you, I've checked in another browser and the button appears for a build on repo where I have write access. I cannot restart the build for this PR though, but I guess I can only do that for a failing one, am I correct?

**Comment by mithro** [comment]
@jedrzejboczar -- You probably don't have the correct permissions on the LiteDRAM GitHub repository to restart builds it seems. As I can do that, @enjoy-digital can you give @jedrzejboczar the same level of permissions as me?

**Comment by enjoy-digital** [comment]
@jedrzejboczar: sorry, i thought you already had the permissions, it should be fine now.

**Comment by enjoy-digital** [comment]
Thanks for the great work @jedrzejboczar, i did a first review and merged it.

**Pull request merged**
