### PR TITLE
Add auto-precharge support

### PR DESCRIPTION
**Pull request by JohnSully**
When the next row to be accessed is different we can embed the precharge command into the read by toggling A10.  This work does that and saves us some command bus traffic.

Its not as efficient area-wise as it could be.  If we could peek into the next cmd_buffer value then we could eliminate the FIFO and row_last registers I added.

Timing was validated via simulation with a Micron Bus Functional model.

### CODE REVIEW

**Comment by JohnSully** [comment]
This represents about 10% faster memory accesses when page conflicts are frequent.  I wouldn't expect it to have any benefit for sequential memory access patterns.

**Comment by enjoy-digital** [comment]
Thanks! I'll review and test very soon.

**Comment by enjoy-digital** [comment]
Thanks, i merging and will try to improve area if needed.

**Comment by enjoy-digital** [comment]
@JohnSully: can you check that this (https://github.com/enjoy-digital/litedram/commit/8ba7fcab236a311f3481f32232154df191f34378) is equivalent to your commit?

**Comment by JohnSully** [comment]
I believe it is equivalent.

**Comment by enjoy-digital** [comment]
Ok thanks.

**Comment by enjoy-digital** [comment]
I just reverted the changes because this was introducing a regression. I'll need to do more simulations before re-integrating that feature.

**Comment by JohnSully** [comment]
Can you let me know what the issue was?  It will help me not repeat similar mistakes in the future.

**Comment by enjoy-digital** [comment]
I don't know yet what is wrong, just that there is a regression. I'll investigate to see what was going on but needed to revert to avoid breaking others projects.

**Comment by JohnSully** [comment]
This issue? https://github.com/enjoy-digital/litedram/issues/14

**Comment by JohnSully** [comment]
Potential issues from code review:
We shouldn't be checking the precharge timer in the AUTOPRECHARGE state.  We would need to either delay the read/write or avoid auto precharge entirely if timing constraints aren't met.  I think the whole AUTOPRECHARGE state was a bug.

**Pull request merged**
