### PR TITLE
phy/model: fix memory addressing issues in some configurations

### PR DESCRIPTION
**Pull request by piotr-binkowski**
This fixes litex-hub/linux-on-litex-vexriscv#104

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks.

**Comment by enjoy-digital** [comment]
@piotr-binkowski: Travis CI is now failing on Linux-on-LiteX-VexRiscv for some configurations: https://github.com/litex-hub/linux-on-litex-vexriscv/runs/453115052 I haven't look closely yet, but do you think it could be related to this change? (that's the last change we did that i think of and that could explain the regression).

**Comment by piotr-binkowski** [comment]
I think that this might be related, from what I see this only affects chips with `nrows  = 65536` and I've modified part of the code that handles addressing. I will look into this

**Comment by enjoy-digital** [comment]
OK thanks.

**Comment by piotr-binkowski** [comment]
I think that I found the issue. It appears that there is another thing that those memories have in common - each one of them is larger than 1GB when used with the default data width(32-bit).
Simulations showed that when CPU was accessing `0x40000000`(DRAM offset 0) LiteDRAM sends read requests for row `0x8000` instead of the expected `0x0000` - somehow already accessing the upper half of the memory while Litex and BIOS state that this memory is only 1 GB in size.
@enjoy-digital could you please take a look at this issue because I think that while my change surfaced the issue in CI, the issue itself might be located in another part of the LiteDRAM core and I'm not sure where to look for it.

**Comment by enjoy-digital** [comment]
Thanks for looking at the issue @piotr-binkowski, i'll continue the investigation.

**Comment by enjoy-digital** [comment]
The issue was that the `base_address` or `main_ram` was not substracted. This was causing issue on large memories since the MSB were passed to the DRAM controller (which was not the case on regular memories since the MSB was truncated). This is fixed with https://github.com/enjoy-digital/litex/commit/f3829cf0819c2e5d0ebc6cffb9569f9f46191549 and this is the first issue found with the new features/tests :)

**Pull request merged**
