### PR TITLE
phy/ecp5ddrphy: invert the clock signal if necessary.

### PR DESCRIPTION
**Pull request by garytwong**
(Please note this pull request depends on https://github.com/enjoy-digital/litex/pull/781.)

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, is it due to a clk pin inversion on a custom board?

**Comment by garytwong** [comment]
Yes indeed... hard to imagine somebody would connect + to - and - to +.  But if that happens, then it's easier to fix the FPGA config than the PCB :smile:

**Comment by enjoy-digital** [comment]
Thanks for the information. The `Inverted` attribute has been done as a quick workaround and not necessarily something I would like to keep (or at least encourage the use) until we found a better solution. So I added with https://github.com/enjoy-digital/litedram/commit/5a114be7e597767b4540a5292e3f13583f4624e3 a `clk_polarity` parameter to ECP5DDRPHY that you can use on you board to invert `clk` polarity.

**Comment by garytwong** [comment]
Thanks! The `clk_polarity` parameter works fine.

**Pull request closed without merging**
