### PR TITLE
phy/model: add basic timing violation checker

### PR DESCRIPTION
**Pull request by piotr-binkowski**
This PR adds a module to PHY model that will check DFI interface timings against timings specified in `modules.py`.
At this point only a limited subset of bank commands is tested

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, this seems to be going in the right direction. I see you are using `dataclasses` which i think are only available in Python3.7. If so, is it difficult to use a Class structure that is compatible with Python3.5? (the rest of the project is still using Python3.5, this will change in the future, but we will need to evaluate the potential compatibility issues first and switch it in every repository at the same time).

**Comment by piotr-binkowski** [comment]
I've noticed that the CI uses older version of Python so I already changed this to use ordinary `Class`

**Comment by enjoy-digital** [comment]
OK, thanks.

**Comment by piotr-binkowski** [comment]
I've added tests for the missing timings and I think that now I cover everything. Only issue I noticed is that until I see `SDRAM now under hardware control` in the console I'm getting constant `tREFI` violations

**Comment by enjoy-digital** [comment]
Great. That's expected to have `tREFI` violations during the initialization since the refreshing is not yet activated. Have you tried corrupting manually some timing_settings values: https://github.com/enjoy-digital/litedram/blob/master/litedram/modules.py#L62 and see if you are able to detect timing violations with the DFI model? For example reduce internal `tRP`, `tREFI` and see if errors are detected?

**Comment by piotr-binkowski** [comment]
I've did some tests where I modified the timing constraints on the `DFITimingsChecker` side and the errors were detected but I will try to do the opposite and modify settings used by the controller

**Comment by piotr-binkowski** [comment]
After some more tests with unmodified settings I see that `tREFI` violations are detected on all memory types other than `SDR`.

**Comment by piotr-binkowski** [comment]
After reducing `tRCD` by one cycle I'm getting the following output
```
litex> mr 0x41000000 256
Memory dump:
0x41000000  [0000101901470000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000020  [0000102375470000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000030  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000040  [0000102823870000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000060  [0000103272270000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000080  [0000103720670000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x41000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000a0  [0000104169070000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000c0  [0000104617470000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000e0  [0000105065870000ps] ACT->RD violation on bank 0
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x410000f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
```
So it looks like detecting even small violations should work

**Comment by enjoy-digital** [comment]
Thanks, i'll look for the `tREFI`. It's possible to postpone and group the refreshes commands, i'll look if that's what is occuring or of the timing checker found the first issue :)

**Comment by piotr-binkowski** [comment]
I've updated the `tREFI` code now to not be so spammy - now it prints out info about a violation and then it needs to be primed again by a refresh command. Further testing using updated code showed no issues with `DDRx` memory that I mentioned before but there might be some `tREFI` violations during a memtest procedure. When running `./tools/litex_sim.py --with-sdram --sdram-module EDY4016A` I've got this:
```
litex> memtest
[0000030662307500ps] tREFI violation
[0000030662347500ps] Late refresh
[0000031538147500ps] tREFI violation
[0000031538217500ps] Late refresh
[0000031678907500ps] tREFI violation
[0000031678967500ps] Late refresh
Memtest OK
[0000032906647500ps] tREFI violation
[0000032906667500ps] Late refresh
Memspeed Writes: 3Mbps Reads: 3Mbps
```

**Comment by enjoy-digital** [comment]
Thanks for the change and `litex_sim` integration. We can merge this initial version.

**Pull request merged**
