### PR TITLE
Allow testing custom access patterns

### PR DESCRIPTION
**Pull request by jedrzejboczar**
PR for issue https://github.com/enjoy-digital/litedram/issues/113.
It adds possibility to run benchmarks using predefined access patterns loaded from simple CSV files. 

It is WIP as currently it is not possible to use custom patterns for `run_benchmarks.py`. I have to modify the way summary is generated to account for cases of custom access pattern, simple latency benchmarks and simultaneous write+read (https://github.com/enjoy-digital/litedram/issues/114). But `run_benchmarks.py` will still work correctly if custom access patterns are not used.

As for the `benchmark.py`, currently there is a limitation that the access pattern cannot write to the same address twice, because this will result in data being overwritten before checker reads them. If needed, this will be easier to implement after https://github.com/enjoy-digital/litedram/issues/114.

I also added two simple helper scripts for generating configuration and access pattern, to this PR can e.g. be run using:
```
./benchmark.py --access-pattern <(./gen_access_pattern.py 0 1024 32)
```

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, this seems fine. In the future, we'll want to be able to use the pattern generator/checker on hardware, so instead of the storing the data/address with `Case` that would be better to use a `Memory`.

**Comment by jedrzejboczar** [comment]
I've rewritten results processing to be more flexible. The benchmark results can have quite different parameters depending on configuration, so to I used [pandas](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html) to keep results processing simpler. Results are now displayed in groups depending on access type to make them comparable. 

Configuration file format has changed a bit to allow for custom access patterns from file. Access pattern cannot be stored directly in the configuration, but we need some name to display it anyway, so we just store access patterns in files and display the name of the file.

**Comment by jedrzejboczar** [comment]
Could we marge this one now? I will be creating a PR related to speeding up the benchmark on top of this one and later I will implement access patterns using `Memory` in a separate PR.

**Comment by enjoy-digital** [comment]
OK it's merged, i just created: https://github.com/enjoy-digital/litedram/issues/134.

**Pull request merged**
