### PR TITLE
Add simulations to Travis CI

### PR DESCRIPTION
**Pull request by mglb**
This PR adds a new stage to Travis CI, which runs litex_sim and linux-on-litex-vexriscv simulations for each sdram module.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @mglb for the PR. just as a general idea, we have to avoid to much circular dependencies. LiteDRAM requires LiteX, Linux-on-LiteX-Vexriscv is an application project and requires LiteX / LiteDRAM (and others cores) be we should avoid LiteDRAM to require one of the application project. So we could run in Travis CI the tests based on LiteX sim, but the tests related to Linux-on-LiteX-Vexriscv should go probably go to https://github.com/litex-hub/linux-on-litex-vexriscv. If we want to be sure that changes to LiteDRAM are not breaking Linux-on-LiteX-Vexriscv, we should find a way to trigger Travis-CI of Linux-on-LiteX-Vexriscv when LiteDRAM is updated.

**Comment by mglb** [comment]
I've removed linux simulations from this PR.

Each simulation test scans simulation output for memtest results. It should work as long as "BIOS built on" and "Memtest OK" strings are printed by the BIOS. Timeouts are at least 7x longer than it is usually needed.

**Comment by enjoy-digital** [comment]
Thanks for the update, merged.

**Comment by enjoy-digital** [comment]
@mglb: FYI, i removed the use of Conda with https://github.com/enjoy-digital/litedram/commit/8316ed3a47c8e402039e3804d8aa916cbe2f0e33. The setup is simple enough here to avoid using it (and i have a preference not using it when possible since it adds dependencies and potential problems).

**Pull request merged**
